@ECHO OFF

:: SET WINDOW SIZE
MODE CON: cols=140 lines=40

:: RUN THE BOT
:RUN
hermbot_3.3.0.exe
ECHO Bot terminated

:: PAUSE AFTER BOT ENDS
PAUSE

GOTO RUN :: RUN THE BOT AGAIN

PAUSE :: PAUSE IN CASE SOMETHING GOES WRONG
